### PR TITLE
set dollar-variable-colon-space-after to always-single-line

### PR DESCRIPTION
**Pull request by woylie**
`'scss/dollar-variable-colon-space-after': 'always'` collides with the default formatting of Prettier when the value is broken into several lines.

For example, Prettier formats like this:

```css
$ratios:
    1 1,
    2 1,
    5 4,
    4 3,
    3 2,
    16 9,
    4 5,
    3 4,
    2 3,
    9 16;
```

While the rule set to `always` formats the same like this:

```css
$ratios: 1 1,
    2 1,
    5 4,
    4 3,
    3 2,
    16 9,
    4 5,
    3 4,
    2 3,
    9 16;
```

I propose to default to a setting that is compatible with Prettier.

### CODE REVIEW

**Comment by kristerkari** [comment]
Thanks @woylie !

Could you also add a test case for this changed to the `valid.scss` file?

**Comment by woylie** [comment]
Hey @kristerkari,

I added the example. I couldn't get the tests to run locally, so I hope this suffices.

**Comment by kbrilla** [comment]
fixes: #165

**Comment by kristerkari** [comment]
Sorry that I missed this one! Looks good now with the test added. 👍

**Pull request merged**
