### PR TITLE
Allow private variables

### PR DESCRIPTION
**Pull request by Chi-teck**
https://sass-lang.com/documentation/at-rules/use#private-members

### CODE REVIEW

**Comment by kristerkari** [comment]
@Chi-teck Thanks! Could you also please update the tests (`valid.scss`) to include the variable format that you want to allow?

**Comment by Chi-teck** [comment]
Done.

**Review by kristerkari — APPROVED** [review]
Looks good! 👍 

(The failing lint command is something that I already fixed in master).

**Comment by kristerkari** [comment]
Thanks a lot @Chi-teck !

Released in 2.0.1:
https://github.com/stylelint-scss/stylelint-config-standard-scss/releases/tag/v2.0.1

**Pull request merged**
